sudo: false
language: android
jdk: oraclejdk7
git:
  submodules: false
android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1
    - android-22

script:
  gradle build
